AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Example API written with SpringBoot with the spring-cloud-function-adapter-aws library

Resources:
  reverseString:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.isoreg.serverless.ServerlessRequestHandler::handleRequest
      Runtime: java8
      CodeUri: ./target/spring-cloud-functions-0.0.1-SNAPSHOT-aws.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Environment:
        Variables:
          ENVIRONMENT: "test"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /findAllBean
            Method: ANY
      #Environment:
      #Variables:
      #FUNCTION_NAME: reverseString
      #MAIN_CLASS: com.isoreg.serverless.CloudFunctionAwsApplication
